"""修改User Admin表

Revision ID: 72d6437ec7e4
Revises: f2ee9ae25792
Create Date: 2018-06-28 02:24:37.273199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72d6437ec7e4'
down_revision = 'f2ee9ae25792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('_password', sa.String(length=100), nullable=True))
    op.drop_index('password', table_name='admin')
    op.create_unique_constraint(None, 'admin', ['_password'])
    op.drop_column('admin', 'password')
    op.add_column('user', sa.Column('_password', sa.String(length=100), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('user', '_password')
    op.add_column('admin', sa.Column('password', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'admin', type_='unique')
    op.create_index('password', 'admin', ['password'], unique=True)
    op.drop_column('admin', '_password')
    # ### end Alembic commands ###
