"""添加权限表

Revision ID: bb87c1bdf9f4
Revises: 2a9c7f2d54a2
Create Date: 2018-06-23 09:44:05.094817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb87c1bdf9f4'
down_revision = '2a9c7f2d54a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=32), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_auth_addtime'), 'auth', ['addtime'], unique=False)
    op.drop_index('avatar', table_name='user')
    op.drop_index('password', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'user', ['password'], unique=True)
    op.create_index('avatar', 'user', ['avatar'], unique=True)
    op.drop_index(op.f('ix_auth_addtime'), table_name='auth')
    op.drop_table('auth')
    # ### end Alembic commands ###
