"""修改Role表

Revision ID: f2ee9ae25792
Revises: bb87c1bdf9f4
Create Date: 2018-06-23 12:53:04.613688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ee9ae25792'
down_revision = 'bb87c1bdf9f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('auths', sa.String(length=100), nullable=True))
    op.add_column('role', sa.Column('name', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'role', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_column('role', 'name')
    op.drop_column('role', 'auths')
    # ### end Alembic commands ###
